server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.10.12:3100/loki/api/v1/push

scrape_configs:
- job_name: k8s
  static_configs:
  - targets:
      - localhost
    labels:
      job: k8s
      __path__: /var/log/containers/*.log