apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    final.project.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      final.project.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        final.project.network/django-pg-docker-tutorial-default: "true"
        final.project.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: tutorial-dev
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: vinhle
          image: postgres:13-alpine
          name: db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: tutorial-volume
      restartPolicy: Always
      volumes:
        - name: tutorial-volume
          persistentVolumeClaim:
            claimName: tutorial-volume
status: {}
