apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    final.project.service: db
  name: db
spec:
  clusterIP: 10.99.26.31
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    final.project.service: db
status:
  loadBalancer: {}
