apiVersion: v1
kind: PersistentVolume
metadata:
  name: tutorial-pv-volume 
spec:
  storageClassName: fast
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    final.project.service: tutorial-volume
  name: tutorial-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 200Mi
status: {}
