name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.HUB_ACCESS_TOKEN }}
    - name: Build the image
       docker build . --file django-pg-docker-tutorial/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/django-app:latest
    - name: Push to Docker Hub
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/django-pg
